### ISSUE TITLE
Stake button should not be enabled when user did not approved Landworks NFTS

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#27]
Stake button should not be enabled when user did not approved Landworks NFTS as the TX will always fail:

![image](https://user-images.githubusercontent.com/12232750/150143189-2a95df10-3c1e-4809-ad68-44758a511447.png)

![image](https://user-images.githubusercontent.com/12232750/150143242-828d2b83-396f-407e-9892-b870502d5b32.png)

**Comment by taskudis** [comment]
Fixed at 6d840cb393430b25b0b44940e5816ebee12d17cf

**Comment by Daniel-K-Ivanov** [comment]
It is still reproducing
![image](https://user-images.githubusercontent.com/12232750/150286219-95873143-f3b1-4d10-b422-c13e5a289ca9.png)

**Comment by taskudis** [comment]
Fixed at eb7f0adace497d02d77ef03f2845e6376ca8f560
